### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by Subass1998** [Minecraftfunize/Youtube-Hacked-Client-1.8#14]
I cant re compile the file so i can give it to my friends it says "!! can not find server sources, try decompiling!!"
and i cant decompile

**Comment by Creeperlover234** [comment]
If you are using the mcp folder to decompile it that's the problem you need to go into eclipse right click "Client" and click export then open java folder and select and unselect .project, and .classpath and then jars and lib so make sure src is highlighted! then once it is on your desktop edit the .jar file and edit the jar file with 7zip and delete MEAT-INF and start.class after that you want to edit slick.jar file you downloaded from the videos and drag in the META-INF from the slick.jar and open org in the slick jar and drag "newdawn" into the org file in your hacked client folder. And that should be it xD

some pics: 


![](http://i.imgur.com/fZPRZpL.png)

**Comment by ConnorCreedGold** [comment]
In that picture there are many classes but when i export i only see folders not classes
